//Language
export const SET_LANGUAGE = "SET_LANGUAGE";

//Auth
export const CREATE_USER_LOADING = "CREATE_USER_LOADING";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILED = "CREATE_USER_FAILED";

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

// API
export const GET_GAMES_DATA_LOADING = "GET_GAMES_DATA_LOADING";
export const GET_GAMES_DATA_SUCCESS = "GET_GAMES_DATA_SUCCESS";
export const GET_GAMES_DATA_FAILED = "GET_GAMES_DATA_FAILED";

// Purchase and install

export const PURCHASE_LOADING = "PURCHASE_LOADING";
export const PURCHASE_SUCCESS = "PURCHASE_SUCCESS";
export const PURCHASE_FAILED = "PURCHASE_FAILED";

export const INSTALL_GAME_LOADING = "INSTALL_GAME_LOADING";
export const INSTALL_GAME_SUCCESS = "INSTALL_GAME_SUCCESS";
export const INSTALL_GAME_FAILED = "INSTALL_GAME_FAILED";

export const LIKE_GAME_LOADING = "LIKE_GAME_LOADING";
export const LIKE_GAME_SUCCESS = "LIKE_GAME_SUCCESS";
export const LIKE_GAME_FAILED = "IKEe_GAME_FAILED";
